server:
  port: 9191

spring:
  application:
    name: dom-ms-app-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://dom-ms-user
          predicates:
            - Path=/ms-users/**
        - id: department-service
          uri: lb://dom-ms-department
          predicates:
            - Path=/ms-departments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream